### ISSUE TITLE
abstract type in quasi.jl

### ISSUE THREAD

**Issue by stevengj** [cscherrer/QuasiMonteCarlo.jl#1]
You define
```jl
struct Quasi{N, F}
    s :: SobolSeq{N}
    x :: AbstractVector{<:AbstractFloat}
    f :: F
end
```
which defines `x` as an abstract type, which will hurt performance of downstream code.  Possibly you want something like
```jl
struct Quasi{N, F, A <: AbstractVector{<:AbstractFloat}}
    s :: SobolSeq{N}
    x :: A
    f :: F
end
```
or maybe just:
```
struct Quasi{N, F, T<:AbstractFloat}
    s :: SobolSeq{N}
    x :: Vector{T}
    f :: F
end
```

You also might add a constructor that adds the `T` argument, e.g. `Quasi(N::Int, T::Type=Float64)`.

(Currently Sobol.jl requires an `AbstractFloat` type for `x`, but in the future I may widen that to `Real`, since it can actually generate `Rational` values if someone wants those.)

**Comment by cscherrer** [comment]
Great point, thanks!
https://github.com/cscherrer/QuasiMonteCarlo.jl/commit/c20539d01a80d10f8989924cf3f6f88a44beabc8
